csv_show_tables:
    path:     /showTablesCsv
    defaults: { _controller: "PlateFormeBundle:Default:showTables" }

csv_show_fields:
    path:     /showFieldsCsv
    defaults: { _controller: "PlateFormeBundle:Default:getTableFields" }
    methods:  [GET, POST]

csv_export:
    path:     /exportCsv
    defaults: { _controller: "PlateFormeBundle:Default:generateCsv2" }
